import Link from 'next/link';
const data:Record<string,{name:string,type:string,summary:string,problem:string,approach:string,impact:string,mark:string}>={
'river-intelligence':{name:'River Intelligence',type:'GIS · Data · Infrastructure',summary:'A spatial intelligence system for understanding rivers, vegetation, settlements and infrastructure as one connected landscape.',problem:'Environmental and infrastructure decisions often sit across disconnected maps, spreadsheets and field observations.',approach:'Layer watershed boundaries, river networks, land cover, habitation and infrastructure; then build views that let teams move from regional patterns to specific sites.',impact:'A reusable spatial workflow that makes complex landscape information easier to explore, communicate and act on.',mark:'RI'},
'project-os':{name:'Project OS',type:'Digital systems · Automation',summary:'A project operating layer that connects progress, documentation, billing and operational decisions.',problem:'Teams lose time when the same project information is re-entered across sheets, reports and trackers.',approach:'Design one structured data model, then expose the right views for planning, billing, procurement and management.',impact:'Less repetitive administration and a clearer chain from field entry to management insight.',mark:'OS'},
'material-flow':{name:'Material Flow',type:'CAPEX · Tracking · Dashboards',summary:'A material movement tracker designed around one simple question: what came in, where did it go, and who approved it?',problem:'Material records become difficult to reconcile when inward, outward, category, location and approval information live in different places.',approach:'Group materials by category, track movement events and expose approval responsibility through a compact operational dashboard.',impact:'A transparent material trail from receipt to destination.',mark:'MF'},
'green-building':{name:'Green Building',type:'Design · Analysis · Sustainability',summary:'A building engineering study combining passive design, water management and performance thinking.',problem:'Sustainability is often treated as a checklist after design rather than a design input.',approach:'Bring orientation, ventilation, rainwater harvesting, wastewater reuse and material choices into the design process.',impact:'A practical framework for connecting building performance with constructability and cost.',mark:'GB'},
'water-network':{name:'Water Network',type:'Hydraulics · GIS · Planning',summary:'A network-planning workflow for translating water infrastructure into a spatial, hydraulic and operational model.',problem:'Pipeline planning needs engineering calculations and spatial context at the same time.',approach:'Combine GIS layers, network topology, demand inputs and hydraulic modelling into a decision-ready workflow.',impact:'Better visibility from scheme-level planning to individual network components.',mark:'WN'},
'site-control':{name:'Site Control',type:'Execution · Billing · Reporting',summary:'A field-to-office workflow for construction execution, quantities, billing and reporting.',problem:'Site progress and commercial records can drift apart when updates are manually reconstructed.',approach:'Structure site information around measurable quantities, drawings, BBS, billing records and progress evidence.',impact:'A cleaner link between what was built, what was measured and what was billed.',mark:'SC'}};
export default async function Case({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=data[slug]??data['river-intelligence'];return <main className="case"><div className="container"><section className="case-head"><div className="eyebrow">Case study / {p.type}</div><h1>{p.name}<span style={{color:'var(--gold)'}}>.</span></h1></section><div className="case-art"><span>{p.mark}</span></div><section className="case-intro"><div><div className="eyebrow">The project</div><p style={{marginTop:18,color:'var(--muted)',fontSize:15,lineHeight:1.6}}>{p.type}</p></div><div><p>{p.summary}</p></div></section>{[['The problem',p.problem],['Our approach',p.approach],['What it changes',p.impact]].map(([title,text])=><section className="about-block" style={{paddingTop:30}} key={title}><div><div className="eyebrow">{title}</div></div><p>{text}</p></section>)}<div style={{padding:'40px 0 120px'}}><Link className="pill" href="/work">← Back to work</Link></div></div></main>}
